runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: static/css

- url: /img
  static_dir: static/img

- url: /fonts
  static_dir: static/fonts

- url: /libs
  static_dir: static/libs

- url: /js
  static_dir: static/js

- url: /pages/.*
  script: src.staticrouter.app

- url: /directives/.*
  script: src.staticrouter.app

- url: /.*
  script: src.staticrouter.app
