runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: static/css

- url: /img
  static_dir: static/img

- url: /fonts
  static_dir: static/fonts

- url: /libs
  static_dir: static/libs

- url: /js
  static_dir: static/js

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /.*
  script: src.staticrouter.app
